spring.application.name=T0-Do-List

# Hibernate ????? tables ????? ?? update ?????
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres

# ????? Username ?? (????? ???????? ????? ???????)
spring.datasource.username=postgres.liglzuutxvgnturznxbd

# ????? ????? Supabase database password ?? ????? (????? ?????)
spring.datasource.password=@$&-()=*%#1029384756

# PostgreSQL Driver ??
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL queries terminal ??? ???????
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect