spring.application.name=T0-Do-List

# Hibernate ????? tables ????? ?? update ?????
spring.jpa.hibernate.ddl-auto=update

# ????? Supabase Database URL ?? (Screenshot ??? ????)
spring.datasource.url=jdbc:postgresql://db.liglzuutxvgnturznxbd.supabase.co:5432/postgres

# Username ??
spring.datasource.username=postgres

# ????? ????? Supabase database password ?? ????? (????? ?????)
spring.datasource.password= @$&-()=*%#1029384756

# PostgreSQL Driver ??
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL queries terminal ??? ???????
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect